# Generated by Django 3.2.7 on 2021-11-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='response',
            new_name='answer',
        ),
    ]
