# Generated by Django 3.2.7 on 2021-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_response_log_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='log',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='num_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
